# Generated by Django 3.1.12 on 2025-04-18 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0002_auto_20250418_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlitherReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255)),
                ('report_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slither_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
