# Generated by Django 3.1.12 on 2025-04-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0003_slitherreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='slitherreport',
            name='status',
            field=models.CharField(default='completed', max_length=50),
        ),
    ]
