# Generated by Django 3.1.12 on 2025-04-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0004_slitherreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slitherreport',
            name='report_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
