# Generated by Django 3.1.12 on 2025-04-22 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0005_auto_20250419_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('transaction_hash', models.CharField(max_length=66, unique=True)),
                ('block_number', models.PositiveBigIntegerField()),
                ('event_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=40)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
