# Generated by Django 3.1.12 on 2025-04-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0006_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=40),
        ),
    ]
