# Generated by Django 3.1.12 on 2025-04-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0007_auto_20250423_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slitherreport',
            name='report_name',
            field=models.CharField(max_length=255),
        ),
    ]
